### ISSUE TITLE
Ubuntu 18.04 DNS resolution is not working for LXD daemon

### ISSUE THREAD

**Issue by zeroware** [lxc/lxd-pkg-snap#32]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.9.93-mainline-rev1
   * LXC version:  3.9
   * LXD version: 3.9
   * Storage backend in use: none

# Issue description

I'm trying to list images

```
lxc image list images:
Error: Get https://images.linuxcontainers.org/streams/v1/index.json: lookup images.linuxcontainers.org on [::1]:53: read udp [::1]:33038->[::1]:53: read: connection refused
```

# Steps to reproduce

 1. snap install lxd on a fresh machine
 2. lxd.migrate
 3. lxd init with default settings

# Information to attach

Preseed : 

```
config: {}
networks:
- config:
    ipv4.address: auto
    ipv6.address: auto
  description: ""
  managed: false
  name: lxdbr0
  type: ""
storage_pools:
- config:
    size: 15GB
  description: ""
  name: default
  driver: btrfs
profiles:
- config: {}
  description: ""
  devices:
    eth0:
      name: eth0
      nictype: bridged
      parent: lxdbr0
      type: nic
    root:
      path: /
      pool: default
      type: disk
  name: default
cluster: null


```

Here is the result of `dig`

```
dig images.linuxcontainers.org

; <<>> DiG 9.11.3-1ubuntu1.3-Ubuntu <<>> images.linuxcontainers.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55491
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;images.linuxcontainers.org.    IN      A

;; ANSWER SECTION:
images.linuxcontainers.org. 360 IN      CNAME   canonical.images.linuxcontainers.org.
canonical.images.linuxcontainers.org. 361 IN A  91.189.88.37
canonical.images.linuxcontainers.org. 361 IN A  91.189.91.21

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Thu Jan 17 13:30:28 UTC 2019
;; MSG SIZE  rcvd: 111
```

Here is the result of `systemd-resolve --status` : 

```Global
         DNS Servers: 10.1.94.8
                      10.1.94.9
          DNS Domain: cloud.online.net
          DNSSEC NTA: 10.in-addr.arpa
                      16.172.in-addr.arpa
                      168.192.in-addr.arpa
                      17.172.in-addr.arpa
                      18.172.in-addr.arpa
                      19.172.in-addr.arpa
                      20.172.in-addr.arpa
                      21.172.in-addr.arpa
                      22.172.in-addr.arpa
                      23.172.in-addr.arpa
                      24.172.in-addr.arpa
                      25.172.in-addr.arpa
                      26.172.in-addr.arpa
                      27.172.in-addr.arpa
                      28.172.in-addr.arpa
                      29.172.in-addr.arpa
                      30.172.in-addr.arpa
                      31.172.in-addr.arpa
                      corp
                      d.f.ip6.arpa
                      home
                      internal
                      intranet
                      lan
                      local
                      private
                      test
```
