### ISSUE TITLE
Missing lxc-net et al

### ISSUE THREAD

**Issue by StyXman** [lxc/lxd-pkg-snap#45]
If I install lxd in *buntu via the deb packages, there's one called `lxc-tools` that includes `systemd` units for bringing up the `lxcbr0` bridge and `dnsmasq` serving dhcp. 

If I install the snap on a CentOS7, I don't get that and my setup is kind of useless.

So, could `lxc-tools` be included in the `lxd` snap? TIA.

**Comment by stgraber** [comment]
`lxcbr0` is a LXC, not a LXD thing.

With LXD, the daemon itself manages bridges, so running `lxd init` will create a bridge with dnsmasq and everything for you and you can create more using `lxc network create`.

**Comment by StyXman** [comment]
I did `lxd init`, these were the answers:

```
# lxd init
Would you like to use LXD clustering? (yes/no) [default=no]: yes
What name should be used to identify this node in the cluster? [default=controller]: 
What IP address or DNS name should be used to reach this node? [default=10.50.110.72]: 
Are you joining an existing cluster? (yes/no) [default=no]: 
Setup password authentication on the cluster? (yes/no) [default=yes]: 
Trust password for new clients: 
Again: 
Do you want to configure a new local storage pool? (yes/no) [default=yes]: 
Name of the storage backend to use (btrfs, dir, lvm) [default=btrfs]: dir
Do you want to configure a new remote storage pool? (yes/no) [default=no]: 
Would you like to connect to a MAAS server? (yes/no) [default=no]: 
Would you like to configure LXD to use an existing bridge or host interface? (yes/no) [default=no]: 
Would you like stale cached images to be updated automatically? (yes/no) [default=yes] 
Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]: yes
config:
  core.https_address: 10.50.110.72:8443
  core.trust_password: *********
networks: []
storage_pools:
- config: {}
  description: ""
  name: local
  driver: dir
profiles:
- config: {}
  description: ""
  devices:
    root:
      path: /
      pool: local
      type: disk
  name: default
cluster:
  server_name: controller
  enabled: true
  member_config: []
  cluster_address: ""
  cluster_certificate: ""
  server_address: ""
  cluster_password: ""
```

As you can see, networks is empty. I thought it would create it.
