### ISSUE TITLE
Folders for instances in "shmounts" disappearing and not being able to mount new disks

### ISSUE THREAD

**Issue by dziebart** [lxc/lxd-pkg-snap#91]
# Required information

 * Distribution: `Ubuntu`
 * Distribution version: `20.04.3 LTS (Focal Fossa)`
 * The output of
   * `lxc --version`
   
```
   4.0.8
```   
   * `lxc --config`
```
  config:
  core.https_address: REMOVED
  images.auto_update_interval: "0"
```
   * `uname -a`
```
Linux HOSTNAME_REMOVED 5.14.0-1011-oem lxc/lxc#11-Ubuntu SMP Mon Dec 13 18:01:14 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
```
   * `cat /proc/self/cgroup`
```
13:freezer:/
12:perf_event:/
11:memory:/user.slice/user-0.slice/session-85712.scope
10:misc:/
9:cpuset:/
8:rdma:/
7:blkio:/user.slice
6:pids:/user.slice/user-0.slice/session-85712.scope
5:net_cls,net_prio:/
4:cpu,cpuacct:/user.slice
3:devices:/user.slice
2:hugetlb:/
1:name=systemd:/user.slice/user-0.slice/session-85712.scope
0::/user.slice/user-0.slice/session-85712.scope
```

# Issue description

Similarly to Issue https://github.com/lxc/lxd/issues/4749 and Issue https://github.com/lxc/lxd/issues/4626 we encountered the problem, that containers, which were running for at least one week having problems mounting new disks into the container. We currently have 4 systems running and this issue arouse on only one system. This is very puzzling due to all 4 systems being set-up the same way.

# Steps to reproduce

We have a running container which has the mounting-issue.
We try to mount a disk:
```
lxc config device add s-c-457-srv-a "test" disk source="/opt" path="/opt/test"
```
No error is encountered during this execution. But inside of the container the folder is not mounted:

```
16:31:28 c-587 /opt # ll
total 4.0K
drwxr-xr-x  8 root root  126 Jan 28 15:47 .
drwxr-xr-x 24 root root 4.0K Jan 14 13:04 ..
drwxr-xr-x  6 root root  115 Jan  4 06:07 certbot
drwxr-xr-x  3 root root   25 Feb 18  2020 cni
drwxr-xr-x  6 root root  147 May  4  2021 mc-redis-analyzer
drwxr-xr-x  4 root root  105 Sep  7 06:44 monitor
drwxr-xr-x  3 root root   32 Sep 18  2019 mwscan
drwxr-xr-x  3 root root   48 Apr 22  2021 solr
16:31:51 c-587 /opt # mount | grep "opt"
RC=1 16:31:54 c-587 /opt #
```

The lxc log of the container itself tells us :

```
lxc s-c-587-srv-a 20220128153117.773 ERROR    lxccontainer - lxccontainer.c:do_lxcapi_mount:5031 - No such file or directory - Could not create shmounts temporary dir
```

And when we take a look at the shmounts folder, we see that only the instances, which can actually mount disks (i.e. instances we restarted) have a folder present :

```
ll /var/snap/lxd/common/mntns/var/snap/lxd/common/shmounts/instances
total 0
drwx--x--x 4 root root 80 Jan 28 16:07 ./
drwx--x--x 4 root root 80 Jan 27 16:21 ../
drwx--x--x 2 root root 40 Jan 28 12:52 s-c-33-srv-a/
drwx--x--x 2 root root 40 Jan 28 16:07 s-c-620-srv-a/
```

When we try to manually create a folder for this non-working instance and then add the disk again we get the following message:

```
Error: Failed to start device "test": Failed to add mount for device inside container: Failed to run: /snap/lxd/current/bin/lxd forkmount lxc-mount -- s-c-587-srv-a /var/snap/lxd/common/lxd/containers /var/snap/lxd/common/lxd/logs/s-c-587-srv-a/lxc.conf /var/snap/lxd/common/lxd/devices/s-c-587-srv-a/disk.test.opt-test /opt/test none 4096: 
```

And the log tells us :

```
lxc s-c-587-srv-a 20220128153738.858 ERROR    lxccontainer - lxccontainer.c:do_lxcapi_mount:5096 - No such file or directory - Failed to move the mount from "/dev/.lxd-mounts/.lxcmount_L175cF" to "/opt/test"
lxc s-c-587-srv-a 20220128153738.858 ERROR    lxccontainer - lxccontainer.c:do_lxcapi_mount:5110 - Success - Wait for the child with pid 1157868 failed
```

So there seems to be the problem moving the mount from the shmount to the designated folder.
If we check our manually created folder we can see, that lxc actually creates the folder:

```
/var/snap/lxd/common/mntns/var/snap/lxd/common/shmounts/instances/s-c-587-srv-a# inotifywatch -r -v .
Establishing watches...
Setting up watch(es) on .
OK, . is now being watched.
Total of 1 watches.
Finished establishing watches, now collecting statistics.
total  access  close_nowrite  open  create  delete  delete_self  filename
5      1       1              1     1       1       0            ./
2      0       0              0     0       0       1            ./.lxcmount_CISHgO/
```

But inside of the container : 

```
/dev/.lxd-mounts # inotifywatch -r -v .
Establishing watches...
Setting up watch(es) on .
OK, . is now being watched.
Total of 1 watches.
Finished establishing watches, now collecting statistics.
No events occurred.
```

... There is actually nothing happening. There seems to be a lost "connection" between the `shmounts`-folder and and the `/dev/.lxd-mounts` folder inside of the container, probably due to the removal of the folder linked to the instance in `/var/snap/lxd/common/mntns/var/snap/lxd/common/shmounts/instances`. As far as I can tell, the folders were removed by lxc itself. 

Again, note that this issue occurred on one of four systems and we can currently not reproduce the problem but we currently have the system still running exhibiting the problem with containers not being able to mount, thus we are available for further questions and experiments. As noted in the issues before, a restart fixes this problem and we can happily mount disks again - sadly, this is not a feasible solution for us. Is there some way for us to "re-establish" this connection to mount disks again? And do you have any idea why these shmount folders would go missing?

Here is also the config of the mount-problem-container (before trying to add any new disk):
```
architecture: x86_64
config:
  boot.autostart: "false"
  image.architecture: amd64
  image.description: Ubuntu bionic amd64 (20211206_07:45)
  image.name: ubuntu-bionic-amd64-default-20211206_07:45
  image.os: ubuntu
  image.release: bionic
  image.serial: "20211206_07:45"
  image.variant: default
  limits.cpu: "10"
  limits.memory: 2048MB
  limits.memory.swap: "false"
  limits.processes: "2000"
  security.nesting: "true"
  security.privileged: "true"
  user.backup.server.status: enabled
  user.modus: disabled
  user.type: server
  volatile.base_image: 07118b8076520c4f19dc3fd3c76f19bb8db2480b672618a0f0ef204d1d59a20e
  volatile.eth0.host_name: vethe60d97bb
  volatile.eth0.hwaddr: 00:16:3e:9c:47:27
  volatile.idmap.base: "0"
  volatile.idmap.current: '[]'
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
  volatile.uuid: 5a7f7a11-db86-44ac-ac09-d3334ad689be
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: default
    size: 25600MB
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
